apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-staging
  namespace: staging
  labels:
    app: hello-world
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
      environment: staging
  template:
    metadata:
      labels:
        app: hello-world
        environment: staging
    spec:
      containers:
      - name: hello-world
        image: PLACEHOLDER_IMAGE
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "staging"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-staging-service
  namespace: staging
spec:
  selector:
    app: hello-world
    environment: staging
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-staging-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: staging.hello-world.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-staging-service
            port:
              number: 80
